# Auto-assign configuration
addReviewers: true
addAssignees: false

reviewers:
  - # Add your team members here
  # - username1
  # - username2

numberOfReviewers: 2

skipDraft: true

# Only assign reviewers for specific file changes
filterLabels:
  include:
    - backend
    - frontend
    - infrastructure

# Auto assign based on file paths
filePathsConfig:
  'apps/**': ['frontend-team']
  'backends/**': ['backend-team']
  'packages/**': ['core-team']
  '.github/**': ['devops-team']
  'docker-compose*.yml': ['devops-team']
  'Dockerfile*': ['devops-team']