apiVersion: apps/v1
kind: Deployment
metadata:
  name: makrcave-backend
  labels:
    app.kubernetes.io/name: makrcave-backend
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: makrcave-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: makrcave-backend
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: api
          image: makrx/makrcave-backend:latest
          ports:
            - containerPort: 8001
          env:
            - name: ENVIRONMENT
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: makrx-secrets
                  key: DATABASE_URL
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: makrx-config
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: makrx-config
                  key: KEYCLOAK_REALM
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: makrx-config
                  key: REDIS_URL
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: makrcave-backend
  labels:
    app.kubernetes.io/name: makrcave-backend
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: makrcave-backend
  ports:
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makrx-events-backend
  labels:
    app.kubernetes.io/name: makrx-events-backend
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: makrx-events-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: makrx-events-backend
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: api
          image: makrx/makrx-events-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: makrx-secrets
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: makrx-events-backend
  labels:
    app.kubernetes.io/name: makrx-events-backend
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: makrx-events-backend
  ports:
    - name: http
      port: 8002
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makrx-store-backend
  labels:
    app.kubernetes.io/name: makrx-store-backend
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: makrx-store-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: makrx-store-backend
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: api
          image: makrx/makrx-store-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: makrx-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: makrx-config
                  key: REDIS_URL
            - name: S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: makrx-config
                  key: S3_ENDPOINT
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: makrx-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: makrx-secrets
                  key: S3_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: makrx-store-backend
  labels:
    app.kubernetes.io/name: makrx-store-backend
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: makrx-store-backend
  ports:
    - name: http
      port: 8003
      targetPort: 8000
