apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: makrx-ecosystem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: makrx-ecosystem
  labels:
    app: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: makrx-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: makrx-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: makrx-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
          defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: makrx-ecosystem
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: makrx-ecosystem
data:
  01-create-databases.sql: |
    -- Create databases for different services
    CREATE DATABASE makrcave_db;
    CREATE DATABASE makrx_events_db;
    CREATE DATABASE makrx_store_db;
    
    -- Create users for different services
    CREATE USER makrcave_user WITH PASSWORD 'makrcave_password';
    CREATE USER makrx_events_user WITH PASSWORD 'makrx_events_password';
    CREATE USER makrx_store_user WITH PASSWORD 'makrx_store_password';
    
    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE makrcave_db TO makrcave_user;
    GRANT ALL PRIVILEGES ON DATABASE makrx_events_db TO makrx_events_user;
    GRANT ALL PRIVILEGES ON DATABASE makrx_store_db TO makrx_store_user;