name: Packages Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build auth package
        run: npm run build --workspace=packages/auth

      - name: Test auth package
        run: npm run test --workspace=packages/auth --if-present

      - name: Build shared package
        run: npm run build --workspace=packages/shared --if-present

