name: Prettier Format Check

on:
  pull_request:
    paths:
      - "apps/gateway-frontend/**"
      - "apps/gateway-frontend-hacker/**"
      - "apps/makrcave/**"
      - "apps/makrx-store/**"
      - "apps/makrx-events/**"
      - "!**/node_modules/**"

jobs:
  prettier:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - gateway-frontend
          - gateway-frontend-hacker
          - makrcave
          - makrx-store
          - makrx-events
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: |
          cd apps/${{ matrix.app }}
          npm ci
      - name: Run Prettier check
        run: |
          cd apps/${{ matrix.app }}
          npx prettier --check .
